# Generated by Django 3.0.8 on 2021-05-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0003_ordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='order',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='orderitem',
            field=models.CharField(max_length=200),
        ),
    ]
